### ISSUE TITLE
Argo CD testing on dev for genegraph migration parity testing

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/architecture#114]
The genegraph migration parity ticket is about running the genegraph migration as a helm chart hook before deploying a new image. The image and the migration will be tied together through migration name containing the actual image sha.

But testing with helm alone on dev proved that there are some subtle differences that need to be accounted for when Argo CD will be in charge of the deployment. Using "helm upgrade" to deploy on dev cluster there were a number of infrastructure artifacts (like SSD and ingress) that had to be manually turned off in the helm values before running the upgrade. Speaking with Steve, he believes this will not be the case for when Argo is in charge. We need to test this before deploying Argo as the deployment strategy for genegraph stage and prod.

**Comment by sjahl** [comment]
I think when we spoke, @theferrit32  helped us realize that the conflicts/"already exists" errors that were arising when using `helm upgrade` were due to some of the resources in the helm charts missing some labels. Helm uses the labels and selectorLabels to determine what objects are part of the chart, and should be OK with proceeding with upgrades if it identifies resources as belonging to the chart. I think the Right Thing, is to ensure that all the resources in the chart have the same base set of labels on them. An example of where this is done correctly is in the clinvar-submitter chart: 

* There's a _helpers.tpl chart with the labels and selectorlabels definition: https://github.com/clingen-data-model/architecture/blob/master/helm/charts/clingen-clinvar-submitter/templates/_helpers.tpl#L33-L51
* Then, every deployment/ingress/service/certificate/etc just includes those helper templates like so: [deployment.yaml#L5-L6](https://github.com/clingen-data-model/architecture/blob/master/helm/charts/clingen-clinvar-submitter/templates/deployment.yaml#L5-L6), [ingress.yaml#L5-L6](https://github.com/clingen-data-model/architecture/blob/master/helm/charts/clingen-clinvar-submitter/templates/ingress.yaml#L5-L6)

It's true that I think Argo doesn't care about this as much, but I still think it'd be a good idea to get the resource labels implemented just as a matter of correctness, and to make the helm chart work for the `helm upgrade` flow, just to ease development deployments going forward.
