### ISSUE TITLE
Update Terraform with production genegraph alerting policy and notification

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/architecture#185]
Ensure terraform reflects the production genegraph policy alerts and notification that I entered manually into GCP

**Comment by sjahl** [comment]
@toneillbroad I'm gonna close this one. The current uptime check lives at: https://github.com/clingen-data-model/architecture/blob/master/terraform/prod/monitoring.tf#L58-L83, and corresponds to the uptime check that we currently rely on.

The alert policy is a slightly different question. The google API doesn't support making alert policies that have the GCP Mobile App as an alert target (which is the case for most of our alerts). Since the API doesn't support it, terraform can't create alert policies that alert the mobile app.

Until either the google API starts supporting that, or we switch so some other alerting mechanism, manually configuring the alert policy on the uptime check like you did is the correct thing to do 👍 

In that monitoring.tf file, there's a bunch of commented out alert policies that could be uncommented if that API changes.
