### ISSUE TITLE
Create continuous deployment to dev cluster for genegraph-dev manifest

### ISSUE THREAD

**Issue by theferrit32** [clingen-data-model/architecture#6]
Depends on https://github.com/clingen-data-model/architecture/issues/3

One possibility discussed is Argo CD

**Comment by theferrit32** [comment]
Perhaps part of this should also be continuous deployment of encrypted dev environment secrets to dev kubernetes cluster, which depends on https://github.com/clingen-data-model/architecture/issues/5

**Comment by sjahl** [comment]
I renamed this since I think the spirit of this issue was for kubernetes deployments, and curator is going to firebase.

The goal for the work on this issue is to get an ArgoCD installation running in the genegraph-dev cluster. Success here means that upon merging changes to the master branch of the architecture repository, Argo will automatically attempt to apply genegraph Deployment in genegraph-dev.

**Comment by sjahl** [comment]
The majority of the goal of this work is done in https://github.com/clingen-data-model/architecture/pull/13

Once that's merged to master, I can toggle on the automatic deployments for the genegraph dev environment (Argo is set to manual deploys still, waiting for the PR to merge.

I'll create an issue for follow-up work (which will focus on productionalizing the argo deployment), but the smaller goal here of getting auto deployments to genegraph-dev should be covered by that PR.
